name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install cargo-nextest via cargo-binstall
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-nextest

    - name: Check
      uses: actions-rs/cargo@v1
      with:
        command: check

    - name: Run tests with cargo nextest
      run: cargo nextest run